'use strict'

const fs = require('fs')
const path = require('path')
const { detectFramework } = require('./detect')
const expressParser = require('./parsers/express')
const fastapiParser = require('./parsers/fastapi')
const nestjsParser = require('./parsers/nestjs')

function getParser(framework) {
  if (framework === 'fastapi' || framework === 'python') return fastapiParser
  if (framework === 'nestjs') return nestjsParser
  return expressParser
}

function analyze(projectRoot) {
  const { framework, name, version, routeFiles, lang } = detectFramework(projectRoot)
  const parser = getParser(framework)
  const allRoutes = []

  for (const file of routeFiles) {
    let content
    try { content = fs.readFileSync(file, 'utf8') } catch { continue }

    const routes = parser.parse(file, content)

    // For Next.js App Router route files, extract HTTP exports
    if (framework === 'nextjs') {
      const nextRoutes = parseNextJsRoute(file, content, projectRoot)
      allRoutes.push(...nextRoutes)
    } else {
      allRoutes.push(...routes)
    }
  }

  return buildSpec(name, version, allRoutes, framework)
}

function parseNextJsRoute(filePath, content, root) {
  const routes = []
  const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD']

  // Detect exported HTTP methods: export async function GET(...) or export { GET }
  const exportRe = /export\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\s*\(/g
  const exportConst = /export\s+const\s+(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\s*=/g

  const foundMethods = new Set()
  let m
  while ((m = exportRe.exec(content)) !== null) foundMethods.add(m[1])
  while ((m = exportConst.exec(content)) !== null) foundMethods.add(m[1])

  if (foundMethods.size === 0) return routes

  // Derive the API path from the file path
  const rel = path.relative(root, filePath).replace(/\\/g, '/')
  let apiPath = '/'

  if (rel.startsWith('app/')) {
    apiPath = '/' + rel
      .replace(/^app\//, '')
      .replace(/\/route\.[jt]s$/, '')
      .replace(/\(([^)]+)\)\//g, '') // remove route groups like (auth)/
      || '/'
    // Convert Next.js [param] to OpenAPI {param}
    apiPath = '/' + apiPath.replace(/\[([^\]]+)\]/g, '{$1}').replace(/^\/+/, '')
  } else if (rel.startsWith('pages/api/')) {
    apiPath = '/' + rel.replace(/^pages\//, '').replace(/\.[jt]sx?$/, '')
      .replace(/\[([^\]]+)\]/g, '{$1}')
  }

  const tag = apiPath.split('/').filter(Boolean)[1] || 'api'

  for (const method of foundMethods) {
    const params = (apiPath.match(/\{([^}]+)\}/g) || []).map(p => ({
      name: p.slice(1, -1), in: 'path', required: true, schema: { type: 'string' },
    }))
    const route = {
      method,
      path: apiPath,
      tag,
      summary: '',
      operationId: method.toLowerCase() + apiPath.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_'),
      parameters: params,
      responses: { '200': { description: 'OK' } },
    }
    if (['POST', 'PUT', 'PATCH'].includes(method)) {
      route.requestBody = { content: { 'application/json': { schema: { type: 'object' } } } }
    }
    routes.push(route)
  }

  return routes
}

function buildSpec(name, version, routes, framework) {
  const paths = {}

  for (const route of routes) {
    if (!paths[route.path]) paths[route.path] = {}
    const method = route.method.toLowerCase()
    if (paths[route.path][method]) continue

    const operation = { operationId: route.operationId, summary: route.summary, tags: [route.tag] }
    if (route.parameters?.length) operation.parameters = route.parameters
    if (route.requestBody) operation.requestBody = route.requestBody
    operation.responses = route.responses

    paths[route.path][method] = operation
  }

  return {
    openapi: '3.0.3',
    info: {
      title: name,
      version,
      description: `API documentation auto-generated by DocuTrack. Framework: ${framework}.`,
    },
    paths,
  }
}

module.exports = { analyze }
